/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://3p5f3janfjbxlkauhzxuexazle.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-molmbrzszjct7mhnoddda4hqvq",
    "aws_cognito_identity_pool_id": "us-east-1:432025ac-e8c9-41a1-a720-db1d347dd974",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_a6k4Psfly",
    "aws_user_pools_web_client_id": "63b0b2gd3rnjn2btqtvhqm0j1b",
    "oauth": {}
};


export default awsmobile;
