/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://3p5f3janfjbxlkauhzxuexazle.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-molmbrzszjct7mhnoddda4hqvq",
    "aws_cognito_identity_pool_id": "us-east-1:dd83f444-ed30-4e5c-a2c6-ec1d8962ac32",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_UoR0nF4S2",
    "aws_user_pools_web_client_id": "6nvieaae98ecabpcr4jvujjjm",
    "oauth": {}
};


export default awsmobile;
